### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by mherman22** [Nakazibwe/PDOSystems-Technical-Interview#1]
Since the `.env` file is ignored in the `.ignore` file, i think there is need to give guideline in the documentation of how to setup the backend to run as expected.

ps add a documentation label

**Comment by mherman22** [comment]
But to run the backend of your app, i have just hard-corded the `MONGODB_URI `to insert this `mongodb://localhost:27017/grace` in order to have it running. Then among your dependencies, `nodemon `is missing yet in the `scripts `you have something like `"start:dev": "nodemon app.js"` which will be used to run the express app.

**Comment by Nakazibwe** [comment]
I will update the dependencies, for nodemon to run locally. I had it globally installed. This is noted. Thanks for the feedback.

**Comment by mherman22** [comment]
i want now close this issue after you update the documentation with the steps on how to setup

**Comment by Nakazibwe** [comment]
Documentation has been updated. As instructed.

**Comment by mherman22** [comment]
see the importance of a good doc!! i am now unblocked 😄
